version: '3'
services:
    web:
        env_file: './.env'
        build: web
        image: 'zrwaite/codegraphs_web:2.0.1'
        ports:
            - '8001:8001'
    redis:
        build: 'redis'
        image: 'zrwaite/codegraphs_redis:1'
        labels:
            com.datadoghq.ad.logs: '[{"source": "redis", "service": "redis"}]'
        restart: 'always'
        ports:
            - '8002:6379'
        command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
        volumes:
            - redis:/data
volumes:
    redis:
        driver: local