version: '3'
services:
    web:
        env_file: './.env'
        build: web
        image: 'zrwaite/codegraphs_web:3.3.3'
        ports:
            - '8001:8001'
        depends_on:
            - "redis2"
    redis2:
        build: 'redis'
        image: 'zrwaite/redis2:1.0'
        restart: 'always'
        ports:
            - '6380:6379'
        command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
        volumes: 
            - redis2:/data
volumes:
    redis2:
        driver: local