version: '3'
services:
    redis:
        build: 'redis'
        restart: 'always'
        ports:
            - '6379:6379'
        command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
        volumes: 
            - redis:/data
volumes:
    redis:
        driver: local