name: Docker Compose CI

on:
    push:
        branches: [master]
        paths:
            - 'docker-compose.yml'
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: populate .env file
              run: |
                  touch .env
                  echo "${{ secrets.env_file }}" >> .env
                  touch web/.env
                  echo "${{ secrets.env_file }}" >> web/.env
            - name: docker login
              env:
                  DOCKER_USER: ${{secrets.DOCKER_USER}}
                  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - name: Build the Docker images
              run: docker compose build
            - name: Docker push
              run: docker compose push
